version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - main
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_URL=postgres://postgres:password@db:5432/postgres 
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    # container_name: my_db

  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db
    volumes:
      - .:/code
    command: python main/manage.py runserver 0.0.0.0:8000
    container_name: api



volumes:
  web:
  postgres_data:
networks:
  main:
    name: main
