version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db
    volumes:
      - .:/code
    command: python main/manage.py runserver 0.0.0.0:8000
  db:
    image: postgres
    restart: always
    networks:
      - main
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

volumes:
  web:

networks:
  main:
    name: main
