openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /brands/:
    get:
      operationId: brands_list
      parameters:
      - in: query
        name: headquarters_country
        schema:
          type: string
      - in: query
        name: name
        schema:
          type: string
      tags:
      - brands
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
          description: ''
  /cars/:
    get:
      operationId: cars_list
      parameters:
      - in: query
        name: brand
        schema:
          type: integer
      - in: query
        name: brand_name
        schema:
          type: string
      - in: query
        name: engine
        schema:
          type: string
      - in: query
        name: exterior_color
        schema:
          type: string
      - in: query
        name: fuel_type
        schema:
          type: string
      - in: query
        name: interior_color
        schema:
          type: string
      - in: query
        name: is_on_sale
        schema:
          type: boolean
      - in: query
        name: mileage
        schema:
          type: string
      - in: query
        name: model
        schema:
          type: integer
      - in: query
        name: model_name
        schema:
          type: string
      - in: query
        name: price
        schema:
          type: string
      - in: query
        name: transmission
        schema:
          type: string
      - in: query
        name: year_max
        schema:
          type: integer
      - in: query
        name: year_min
        schema:
          type: integer
      tags:
      - cars
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
          description: ''
  /cars/all/:
    get:
      operationId: cars_all_list
      parameters:
      - in: query
        name: brand
        schema:
          type: integer
      - in: query
        name: brand_name
        schema:
          type: string
      - in: query
        name: engine
        schema:
          type: string
      - in: query
        name: exterior_color
        schema:
          type: string
      - in: query
        name: fuel_type
        schema:
          type: string
      - in: query
        name: interior_color
        schema:
          type: string
      - in: query
        name: is_on_sale
        schema:
          type: boolean
      - in: query
        name: mileage
        schema:
          type: string
      - in: query
        name: model
        schema:
          type: integer
      - in: query
        name: model_name
        schema:
          type: string
      - in: query
        name: price
        schema:
          type: string
      - in: query
        name: transmission
        schema:
          type: string
      - in: query
        name: year_max
        schema:
          type: integer
      - in: query
        name: year_min
        schema:
          type: integer
      tags:
      - cars
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
          description: ''
  /models/:
    get:
      operationId: models_list
      parameters:
      - in: query
        name: body_style
        schema:
          type: string
      - in: query
        name: brand_name
        schema:
          type: string
      - in: query
        name: name
        schema:
          type: string
      - in: query
        name: year_max
        schema:
          type: integer
      - in: query
        name: year_min
        schema:
          type: integer
      tags:
      - models
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Model'
          description: ''
  /user/create/:
    post:
      operationId: user_create_create
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /user/login/:
    post:
      operationId: user_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
components:
  schemas:
    Brand:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        headquarters_country:
          type: string
          maxLength: 150
      required:
      - headquarters_country
      - id
      - name
    Car:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        brand_name:
          type: string
        model_name:
          type: string
        year_of_issue:
          type: integer
        price:
          type: string
          maxLength: 150
        mileage:
          type: string
          maxLength: 150
        exterior_color:
          type: string
          maxLength: 150
        interior_color:
          type: string
          maxLength: 150
        fuel_type:
          type: string
          maxLength: 150
        transmission:
          type: string
          maxLength: 150
        engine:
          type: string
          maxLength: 50
        is_on_sale:
          type: boolean
        brand:
          type: integer
        model:
          type: integer
      required:
      - brand
      - brand_name
      - engine
      - exterior_color
      - fuel_type
      - id
      - interior_color
      - mileage
      - model
      - model_name
      - price
      - transmission
      - year_of_issue
    Model:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        year_of_issue:
          type: integer
          maximum: 2147483647
          minimum: 0
        body_style:
          type: string
          maxLength: 50
        brand:
          type: integer
      required:
      - body_style
      - brand
      - id
      - name
      - year_of_issue
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
        confirmed_password:
          type: string
          writeOnly: true
      required:
      - confirmed_password
      - id
      - password
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
