# Generated by Django 4.2.1 on 2023-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_alter_car_mileage_alter_car_price"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favourite_cars",
            field=models.ManyToManyField(related_name="users", to="cars.car"),
        ),
    ]
