# Generated by Django 4.2.1 on 2023-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="def", max_length=60),
            preserve_default=False,
        ),
    ]
