# Generated by Django 4.2.1 on 2023-06-13 12:14

from django.db import migrations, models


def change_username(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(email__isnull=False).update(username=models.F("email"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_username"),
    ]

    operations = [
        migrations.RunPython(change_username, elidable=True),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
