# Generated by Django 4.2.1 on 2023-06-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0007_car_created_at_car_updated_at"),
        ("core", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favourite_cars",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="cars.car"
            ),
        ),
    ]
