# Generated by Django 4.2.1 on 2023-05-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_car_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="condition",
            field=models.CharField(
                choices=[("new", "New"), ("used", "Used")], default="new", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(default=2010),
            preserve_default=False,
        ),
    ]
