# Generated by Django 4.2.1 on 2023-05-12 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_car_condition_car_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="year_of_issue",
        ),
    ]
