# Generated by Django 4.2.1 on 2023-05-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_alter_car_mileage_alter_car_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="cars.brand",
            ),
        ),
    ]
